version: "2.1"

services:
  postgres:
    image: "postgres"
    healthcheck:
      test: exit 0
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=task_list_api_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  testenv:
    build: .
    command: tail -f /dev/null
    environment:
      - SQLALCHEMY_TEST_DATABASE_URI=postgresql+psycopg2://postgres:postgres@localhost:5432/task_list_api_test
      - NODE_ENV=test
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
