"""empty message

Revision ID: 66f8a954dbcc
Revises: 97338d118e6e
Create Date: 2021-05-12 15:07:39.987865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f8a954dbcc'
down_revision = '97338d118e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###
