"""empty message

Revision ID: 01aa13e98a34
Revises: ec1d39dcb4c8
Create Date: 2021-05-11 22:40:18.168868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01aa13e98a34'
down_revision = 'ec1d39dcb4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('matching_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['matching_goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'matching_goal_id')
    # ### end Alembic commands ###
