"""empty message

Revision ID: 0707ac3956c0
Revises: e6da4806b128
Create Date: 2021-05-09 12:28:34.485644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0707ac3956c0'
down_revision = 'e6da4806b128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('main_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['main_goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'main_goal_id')
    # ### end Alembic commands ###
