"""empty message

Revision ID: 0b0197f93cdf
Revises: b30dac682d4f
Create Date: 2021-05-05 12:35:41.039681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0197f93cdf'
down_revision = 'b30dac682d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('brittany', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'brittany')
    # ### end Alembic commands ###
