"""empty message

Revision ID: 128f118e37bb
Revises: 22968bb434f5
Create Date: 2021-05-08 23:39:55.754596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128f118e37bb'
down_revision = '22968bb434f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
