"""empty message

Revision ID: 147ec7e4ecee
Revises: 7f002951fd45
Create Date: 2021-05-11 05:12:17.668032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147ec7e4ecee'
down_revision = '7f002951fd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
