"""empty message

Revision ID: 1b4c721059dd
Revises: 2d846581fa16
Create Date: 2021-05-12 00:27:08.504853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4c721059dd'
down_revision = '2d846581fa16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('goal', sa.Column('description', sa.String(), nullable=True))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'description')
    op.drop_column('goal', 'completed_at')
    # ### end Alembic commands ###
