"""empty message

Revision ID: 1cfb6e9ac5ef
Revises: 0b0197f93cdf
Create Date: 2021-05-05 12:37:55.551305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfb6e9ac5ef'
down_revision = '0b0197f93cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'brittany')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('brittany', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
