"""empty message

Revision ID: 22968bb434f5
Revises: aa5e2b65407c
Create Date: 2021-05-06 11:16:40.631223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22968bb434f5'
down_revision = 'aa5e2b65407c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
