"""empty message

Revision ID: 45be87b8c530
Revises: aa2589766ebf
Create Date: 2021-05-10 18:48:46.651780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45be87b8c530'
down_revision = 'aa2589766ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
