"""establishes model one to many relationship

Revision ID: 634bb8d47af6
Revises: 686f6021dc4d
Create Date: 2021-05-12 20:37:13.653614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634bb8d47af6'
down_revision = '686f6021dc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
