"""adds goal model

Revision ID: 686f6021dc4d
Revises: 6f733261acc6
Create Date: 2021-05-12 17:46:06.612043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686f6021dc4d'
down_revision = '6f733261acc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
