"""empty message

Revision ID: 708fd8e1f47f
Revises: 1d3cd5d2048e
Create Date: 2021-05-10 17:17:39.480925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708fd8e1f47f'
down_revision = '1d3cd5d2048e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
