"""empty message

Revision ID: 71b641b3cbc8
Revises: cbab4291919f
Create Date: 2021-05-09 18:06:00.445860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71b641b3cbc8'
down_revision = 'cbab4291919f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_column('task', 'complete_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complete_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
