"""empty message

Revision ID: 722de67888ed
Revises: 43ee65fced38
Create Date: 2021-05-11 12:59:03.376749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722de67888ed'
down_revision = '43ee65fced38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
