"""empty message

Revision ID: 724c5f362b88
Revises: 32ff77288048
Create Date: 2021-05-11 13:39:39.535973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724c5f362b88'
down_revision = '32ff77288048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('connected_goal', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['connected_goal'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'connected_goal')
    # ### end Alembic commands ###
