"""empty message

Revision ID: 7325a3cbdc46
Revises: 848a9211d197
Create Date: 2021-05-12 17:46:47.020346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7325a3cbdc46'
down_revision = '848a9211d197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_owner_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'goal', ['owner_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_owner_id_fkey', 'task', 'task', ['owner_id'], ['task_id'])
    # ### end Alembic commands ###
