"""Adds goal model

Revision ID: 7378f6a3f013
Revises: 9650f76d2cf0
Create Date: 2021-05-06 11:01:52.314559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7378f6a3f013'
down_revision = '9650f76d2cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('task', 'task_id')
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
