"""empty message

Revision ID: 806931e822b7
Revises: 0626c74f1013
Create Date: 2021-05-05 19:25:49.105915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806931e822b7'
down_revision = '0626c74f1013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
