"""empty message

Revision ID: 848a9211d197
Revises: 1b4c721059dd
Create Date: 2021-05-12 17:42:21.006564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '848a9211d197'
down_revision = '1b4c721059dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'description')
    op.drop_column('goal', 'completed_at')
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['owner_id'], ['task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'owner_id')
    op.add_column('goal', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('goal', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
