"""empty message

Revision ID: 921124bdaf5a
Revises: 227ca7dd42f1
Create Date: 2021-05-10 14:54:38.184328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921124bdaf5a'
down_revision = '227ca7dd42f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(length=240), nullable=True))
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
