"""empty message

Revision ID: 9536727ca70b
Revises: 500df4f33594
Create Date: 2021-05-07 20:46:51.092069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9536727ca70b'
down_revision = '500df4f33594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
