"""empty message

Revision ID: 97338d118e6e
Revises: 7072147e830c
Create Date: 2021-05-11 10:24:04.394314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97338d118e6e'
down_revision = '7072147e830c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
