"""empty message

Revision ID: 978b339f7155
Revises: 39fb0982d5fb
Create Date: 2021-05-06 11:17:58.674115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978b339f7155'
down_revision = '39fb0982d5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
