"""empty message

Revision ID: 9d1ce39d9cb7
Revises: 7c3c8cb5303b
Create Date: 2021-05-11 12:36:49.698682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1ce39d9cb7'
down_revision = '7c3c8cb5303b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
