"""empty message

Revision ID: 9f87b42f3a81
Revises: ed388af3be73
Create Date: 2021-05-11 22:31:46.025397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f87b42f3a81'
down_revision = 'ed388af3be73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_goal_goal_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    op.drop_column('task', 'goal_goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_goal_goal_id_fkey', 'task', 'goal', ['goal_goal_id'], ['goal_id'])
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
