"""empty message

Revision ID: b317a67b511e
Revises: ebe3f951c509
Create Date: 2021-05-10 19:00:35.670800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b317a67b511e'
down_revision = 'ebe3f951c509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goals_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'goals', ['goals_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'goals_id')
    # ### end Alembic commands ###
