"""empty message

Revision ID: b5e27277c35f
Revises: 1d08448e6c2b
Create Date: 2021-05-05 00:17:41.643437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5e27277c35f'
down_revision = '1d08448e6c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', postgresql.ARRAY(postgresql.TIME()), autoincrement=False, nullable=True, comment='Time stamp when completed '))
    # ### end Alembic commands ###
