"""empty message

Revision ID: cb1a2f62aaab
Revises: dfae13cbd321
Create Date: 2021-05-12 15:54:50.253267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1a2f62aaab'
down_revision = 'dfae13cbd321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.create_foreign_key(None, 'task', 'goal', ['goal'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'goal',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
