"""task model updated.

Revision ID: cbab4291919f
Revises: 970d25a8f773
Create Date: 2021-05-09 17:57:42.157108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbab4291919f'
down_revision = '970d25a8f773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complete_at')
    # ### end Alembic commands ###
