"""empty message

Revision ID: da53a789412b
Revises: d972dc8a8b1c
Create Date: 2021-05-07 11:49:01.446154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da53a789412b'
down_revision = 'd972dc8a8b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
