"""empty message

Revision ID: fcd49fc09d2d
Revises: 2d37d7b06da5
Create Date: 2021-05-11 12:36:30.333044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd49fc09d2d'
down_revision = '2d37d7b06da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_name')
    # ### end Alembic commands ###
